### ISSUE TITLE
Tool cannot work on Win7 os.

### ISSUE THREAD

**Issue by rtfingc** [4d61726b/VirtualKD-Redux#1]
Hello. Forgive for my poor English.
I update VMware to `15.5.0 build-14665864` and I found virtualkd 3.0 down.
VirtualKD-Redux can work on Win10 os.
But it cannot work on Win7 os. 
And I have no idea how to fix it.

**Comment by 4d61726b** [comment]
@rtfingc: Was it the 32 or 64 bit version of Windows 7? Did it have service pack 1 installed? Which language version was it?

**Comment by rtfingc** [comment]
> @rtfingc: Thanks. I will see if I can try to reproduce the issue.
> 
> Questions:
> 
> 1. Windows 7 was running in the virtual machine or on the host?
> 2. Was it the 32 or 64 bit version of Windows 7?
> 3. Did it have service pack 1 installed?
> 4. Which language version was it?

1. host: win10 1903 ;  win7 virtual machine (vmware)
2. I had tried x86 and x64 version
msdn -> cn_windows_7_enterprise_with_sp1_x64_dvd_u_677685.iso
`ed2k://|file|cn_windows_7_enterprise_with_sp1_x64_dvd_u_677685.iso|3265574912|E9DB2607EA3B3540F3FE2E388F8C53C4|/`
msdn -> cn_windows_7_enterprise_with_sp1_x86_dvd_u_677716.iso
`ed2k://|file|cn_windows_7_enterprise_with_sp1_x86_dvd_u_677716.iso|2502856704|B3C25EA4DD88D7E54F22D3C3E78C410B|/`
3. Language is Chinese

**Comment by 4d61726b** [comment]
I briefly tried one of the Windows 7 evaluation VM images from Microsoft's site and it worked flawlessly: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I'll do some research and look through the code to see if I can figure out why it would fail in your circumstance. Thanks.

**Comment by 4d61726b** [comment]
@rtfingc: Can you try again with a fresh VM and 2019.3?

**Comment by rtfingc** [comment]
> @rtfingc: Can you try again with a fresh VM and 2019.3?

It is not work yet (T . T). I had also try  IE8-win7-vmware from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and still the same problem. May be there is something wrong with my environment setup.

**Comment by 4d61726b** [comment]
> It is not work yet (T . T). I had also try IE8-win7-vmware from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and still the same problem. May be there is something wrong with my environment setup.

Are you sure that you're pressing F8 at boot and selecting **"Disable Driver Signature Enforcement"**? I am able to reproduce your issue in Windows 7 if i do not select that option. In Windows 7 it is second from the bottom. This is a different spot than Windows 10.

<img width="767" alt="boot options" src="https://user-images.githubusercontent.com/55967456/66664033-cd0c8c80-ec19-11e9-93d2-717ff30987f1.png">

**Comment by rtfingc** [comment]
> > It is not work yet (T . T). I had also try IE8-win7-vmware from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ and still the same problem. May be there is something wrong with my environment setup.
> 
> Are you sure that you're pressing F8 at boot and selecting **"Disable Driver Signature Enforcement"**? I am able to reproduce your issue in Windows 7 if i do not select that option. In Windows 7 it is second from the bottom. This is a different spot than Windows 10.
> 
> <img alt="boot options" width="767" src="https://user-images.githubusercontent.com/55967456/66664033-cd0c8c80-ec19-11e9-93d2-717ff30987f1.png">

Oh，it work.  It is no need to press F8 in win7 before. I forgot this point :(. Thanks a lot for your help!!

**Comment by 4d61726b** [comment]
That's correct. The kdcom binary is not signed in Redux which is why it's required. Good to hear it's working, thanks.

**Comment by frustreated** [comment]
success when disabled the Disable Driver Signature Enforcement.
guest is win7x86
host is win10
