### ISSUE TITLE
"cn_windows_7_professional_with_sp1_x64_dvd_u_677031.iso"  can not boot

### ISSUE THREAD

**Issue by yang123vc** [4d61726b/VirtualKD-Redux#10]
"cn_windows_7_professional_with_sp1_x64_dvd_u_677031.iso"  can not boot

**Comment by 4d61726b** [comment]
Can you please fill out the "Bug report" issue template?

**Comment by 4d61726b** [comment]
Closing for now. I don't believe this is a VirtualKD-Redux issue. If you still believe it is, open a new ticket but fill out the issue template.
