### ISSUE TITLE
can't select windbg preview path

### ISSUE THREAD

**Issue by pyq881120** [4d61726b/VirtualKD-Redux#12]
1. my host is win10 10.0.18362.356
2. VirtualKD-Redux 2020.1
windbg preview and Custmo radio checkbox can't click, now i'm run windbg preview, File-->Attach to Kernel , replace pipe name to VirtualKD-Redux  Pipe name(eg: kd_Win7_x86) , final attach success

**Comment by 4d61726b** [comment]
Can you attach a screenshot of the vmmon window?

**Comment by pyq881120** [comment]
![1](https://user-images.githubusercontent.com/728727/81462546-d678ca00-91e5-11ea-8b3d-834104499b90.png)

**Comment by 4d61726b** [comment]
I see the issue, your debugger type somehow got set to 1 (WINDBG.EXE) and the radio buttons are in a stuck state because that radio button is disabled.

A temporary workaround is to change HKLM\SOFTWARE\BazisSoft\KdVMWare\Monitor\DebuggerType to 3. I will fix this in 2020.2. Thanks.

**Comment by pyq881120** [comment]
now it work fine, but i select windbg preview path with
C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2001.2001.0_neutral__8wekyb3d8bbwe\DbgX.Shell, and start debugger automatically checked, the debugger can't automatic popup，I try click Run Debugger button， Also can't work，Do you need to restart after modification?

**Comment by 4d61726b** [comment]
No, you shouldn't have to reboot. Additionally, it was unncessary to specify Windbg Preview path because you didn't sideload it, you're using the version from the Microsoft Store.

It seems to be in a bad state, but I'm sure how we got there. Can you either attach a screenshot of "HKLM\SOFTWARE\BazisSoft\KdVMWare\Monitor" or attach an exported reg file so I can see all the values to try and reproduce it on my side?

**Comment by pyq881120** [comment]
![BazisSoft reg](https://user-images.githubusercontent.com/728727/81463994-b7cc0080-91f0-11ea-91e7-23ebe33ffd05.PNG)

Delete the .png suffix and then import

**Comment by pyq881120** [comment]
[BazisSoft.reg.zip](https://github.com/4d61726b/VirtualKD-Redux/files/4602663/BazisSoft.reg.zip)

Delete the .zip suffix and then import

**Comment by 4d61726b** [comment]
That configuration works for me...

Can you try something:
1. Close vmmon
2. Delete "PreviewPath" from HKLM\SOFTWARE\BazisSoft\KdVMWare\Monitor
3. Open vmmon
4. Click the radio button for "Windbg Preview". **Do not click the button to set the sideloaded path**
5. Click "Run Debugger"

This will try to load it a different way. Did that work?

If that didn't work, can you open up cmd.exe and type "windbgx" (without the quotes). Does that load Windbg Preview?

**Comment by pyq881120** [comment]
now everything work fine, Thank you for providing such a good tool

**Comment by 4d61726b** [comment]
Cool. Thanks for finding that bug.

**Comment by stonedreamforest** [comment]
> That configuration works for me...
> 
> Can you try something:
> 
> 1. Close vmmon
> 2. Delete "PreviewPath" from HKLM\SOFTWARE\BazisSoft\KdVMWare\Monitor
> 3. Open vmmon
> 4. Click the radio button for "Windbg Preview". **Do not click the button to set the sideloaded path**
> 5. Click "Run Debugger"
> 
> This will try to load it a different way. Did that work?
> 
> If that didn't work, can you open up cmd.exe and type "windbgx" (without the quotes). Does that load Windbg Preview?

it's still can't launch:

![Qf6ulFW6CW](https://user-images.githubusercontent.com/16742566/88275299-b7cb9f00-cd0f-11ea-95a8-2db0297d9f1a.gif)

**Comment by 4d61726b** [comment]
Thanks for finding that issue. This will be fixed in the next release.

**Comment by jessica0f0116** [comment]
i have the same issue still
