### ISSUE TITLE
Anybody else seen oddities with 1909->2004 upgrade with VirtualKD-Reux

### ISSUE THREAD

**Issue by rodwiddowson** [4d61726b/VirtualKD-Redux#17]
Not so much a bug as a "hmmm any one else seen this?"

I just trued to update one of my VMs to 2004 from the DVD and it failed until such time as I uninstalled a particular companies driver.   I am used to the funkiness for WU so that was a "whatever".  The odd thing was after I got up to 2004 and reinstalled the driver would be uninstalled on reboot _unless I rebooted without virtual-KD_.

Once I had done that and established that the driver was there I could reboot with the debugger enabled just fine.

This is just weird and I don't have many cycles to debug it, but I wondered if anyone else had seen anything similar?

IF not, just close this issue - it isn't a bug (in VirtualKD) or anything, just weird.

**Comment by 4d61726b** [comment]
I have not seen that before. So just to clarify, you had to boot at least once with driver signature enforcement enabled (e.g. normal boot) and then everything was fine afterwards?
