### ISSUE TITLE
Still works with VMware 16.0.0?

### ISSUE THREAD

**Issue by SpriteOvO** [4d61726b/VirtualKD-Redux#19]
Hey, I noticed that _VMware Workstation Pro_ recently released version 16.0.0, does _VirtualKD-Redux_ still work?

Have a nice day! 😄

**Comment by 4d61726b** [comment]
I just verified that VirtualKD-Redux still works with VMware Workstation Pro 16. Tried it with the new user mode VMM and the kernel mode VMM.
