### ISSUE TITLE
Still cannot find RPC dispatcher table. Try another VMWare version :-(

### ISSUE THREAD

**Issue by PidanXU** [4d61726b/VirtualKD-Redux#2]
stiil got "Still cannot find RPC dispatcher table. Try another VMWare version :-("

**Comment by 4d61726b** [comment]
If you're seeing "Try another VMWare version :-(", it's because you're not using the vmmon64 from Redux, you're using the original VirtualKD. I changed that string in Redux. Please try it again with VirtualKD-Redux.

**Comment by PidanXU** [comment]
Thank you!After I change VirtualKD-Redux-2019.0 to VirtualKD-Redux-2019.2 ,it works!
