### ISSUE TITLE
Win7SP1,Can not boot.

### ISSUE THREAD

**Issue by tzf-key** [4d61726b/VirtualKD-Redux#20]
**Describe the bug**
In cn_ windows_ 7_ enterprise_ with_ sp1_ On x64 system, the vminstall program in the installation target64 folder cannot be started. It always enters the automatic repair interface of windows system.

**To Reproduce**
1.Install pure win7 SP1
2.Install vminstall under the target64 folder
3.Restart boot, there will be an this BUG

**Expected behavior**
It should be a normal boot

**Screenshots**
1.
![图片](https://user-images.githubusercontent.com/51747553/94554592-e4121780-028c-11eb-8e35-e822aac3d05b.png)
2.
![图片](https://user-images.githubusercontent.com/51747553/94554911-5be04200-028d-11eb-893a-ce39e3e1ae2f.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version  2020.3
 - VMware or VirtualBox version VMware Workstation 16.0.0 build-16894299
 - OS running on the host Windows 10 1809 64-bit
 - OS running in the guest Windows 7 SP1 64-bit:cn_windows_7_enterprise_with_sp1_x64_dvd_u_677685.iso

**Additional context**
Nothing

**Comment by 4d61726b** [comment]
That is expected behavior if you just press enter for that entry. You have to press F8 and then select "Disable Driver Signature Enforcement".

Did you have this issue after disabling driver signature enforcement?
