### ISSUE TITLE
Not detecting Virtualbox 6.x?

### ISSUE THREAD

**Issue by AlexanderBarnt** [4d61726b/VirtualKD-Redux#22]
i am using VirtualKd Redux 2020.4 and it seems not to work with Virtualbox, it does not show the virtual machines in the list.
i am using VirtualBox 6.1.16, any idea? thanks

**Comment by 4d61726b** [comment]
I have not been maintaining the Virtualbox side of VirtualKD-Redux. Instead, all the work has been for VMware Workstation Pro. I briefly tried out Virtualbox a few months ago and determined that it needs a bit of work.

I don't have a timeline yet as to if / when I'll fix it for VirtualBox. In the meantime, have you tried VirtualKD 3.0 to see if that works?

**Comment by AlexanderBarnt** [comment]
VIrtualKD 3.0 does not work either. i hope there it will be fixed if possible.

**Comment by LordNoteworthy** [comment]
Having exactly same issue as @AlexanderBarnt. When I try `VirtualBoxIntegration.exe` to enable my VM, it shows the same exception.

Would be nice to get VirtualBox support back again as it is a free hypervisor and there are probably many people using it.

Cheers.

**Comment by 4d61726b** [comment]
I was able to throw together some code and got it working with the latest version of VirtualBox (6.1.16). I will continue working on it next weekend.

There appears to be an issue of needing a signed kdclient DLL to be loaded in the VirtualBox process. I don't have a good workaround for this yet that I'd be comfortable with releasing.

**Comment by LordNoteworthy** [comment]
Maybe a self signed cert we can install in the Windows certificate store ?

**Comment by 4d61726b** [comment]
Support for the latest version of VirtualBox has been added to 2020.5. Take a look at the updated tutorial [here](https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md).

If there is an issue, you can open up a new ticket or comment on this one.
