### ISSUE TITLE
Virtualbox fails to load kdclient64.dll when starting a Win10 VM

### ISSUE THREAD

**Issue by aaptel** [4d61726b/VirtualKD-Redux#26]
**Describe the bug**
I cannot get VirtualKD to work. I've followed the tutorial, including installing the certs on the host. Virtualbox fails to load kdclient64.dll

**To Reproduce**
- Close VB
- Run VirtualBoxIntegration
- Enable my freshling installed Win10 VM
- Start vmmon64
- Go back to VirtualBoxIntegration window, click Launch VirtualBox
- In virtual box, boot the Win10 VM
- Popup that VB cannot load kdclient64.dll
- Cannot attach debugger (clicking on Run Debugger doesnt do anything)

**Expected behavior**
I expected the Run Debugger to do its thing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1716247/110222088-0fe69880-7ed0-11eb-8e19-0720843daddd.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version 2020.5
 - VirtualBox Version 6.1.18 r142142 (Qt5.6.2)
 - OS running on the host: Windows 20H2 OS Build 19042.804
 - OS running in the guest: Windows 1809 OS Build 17763.1039

**Comment by 4d61726b** [comment]
Can you post the logs for this VM? If you right click the VM in the VirtualBox Manager there is a "Show Log..." button.

Upload the last VBox and VBoxHardening log files. Thanks.

**Comment by aaptel** [comment]
Sorry I needed to get this working fast and was getting really frustrated so I (tried) uninstalled VirtualKD and started from scratch from a new VM using regular built-in kdnet (windbg NET debug). I don't have the logs anymore

**Comment by 4d61726b** [comment]
I tried it with the versions you used and everything worked on my end. My guess based on that limited error message was that you never imported VKD-Redux_CA.cer to the Trusted Root Certification Authorities certificate store.

If you run into this issue again in the future and are able to post the logs, feel free to reopen the ticket. Thanks.

**Comment by aaptel** [comment]
I imported the cert (right click, install cert, selected Local Machine) as I mentioned in the report. I still have it probably. Are you sure the code is signed with the right cert?

**Comment by aaptel** [comment]
![image](https://user-images.githubusercontent.com/1716247/110243142-6e0b8e00-7f59-11eb-974c-99ab22840e69.png)

**Comment by 4d61726b** [comment]
Intermediate Certification Authorities != Trusted Root Certification Authorities. Its in the wrong certificate store.

**Comment by aaptel** [comment]
Hm ok weird, I followed the instructions on the tutorial though. Maybe it's missing something to make that cert stored as Root cert?

**Comment by 4d61726b** [comment]
You have to explicitly choose where to install the certificate in the wizard. You can't let Windows decide for you, otherwise it can put it in the wrong store. I think that was your issue. See screenshot for correct usage.

![image](https://user-images.githubusercontent.com/55967456/110243364-0ee15580-7f28-11eb-8c81-800102c53d64.png)

**Comment by aaptel** [comment]
Ok well I'll remember next time :) thanks
