### ISSUE TITLE
VirtualBoxIntegration crash

### ISSUE THREAD

**Issue by LordNoteworthy** [4d61726b/VirtualKD-Redux#27]
**Describe the bug**
When I open VirtualBoxIntegration in my host, I get the following exception:

![image](https://user-images.githubusercontent.com/5129564/111568655-5c4a9780-875e-11eb-824a-a445ed9c6f6e.png)

**To Reproduce**
As suggested in the doc, Vbox is closed.
Just run VirtualBoxIntegration.exe with or without admin priv.

**Expected behavior**
A GUI to be able to enable the VM.

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2019.4]:  VirtualKD-Redux-2020.5
 - VMware or VirtualBox version [e.g. VMware Workstation 15.5.0 build-14665864]: VirtualBox  6.1.18
 - OS running on the host [e.g. Windows 10 1903 64-bit]: Windows 10 19042 20H2 64 bits.
 - OS running in the guest VM [e.g. Windows 7 SP1 32-bit]: Windows 7 SP1 64-bit

**Additional context**

Cheers.

**Comment by LordNoteworthy** [comment]
Quickly debugged the app, and here is the issue:

Here is how my VMs looks like
![image](https://user-images.githubusercontent.com/5129564/111569551-1c84af80-8760-11eb-9cdc-ed5124fe454e.png)

As you can see, some VMs are still registered within VBox Serverm though they are deleted in disk. It crashes when you try to access the `.name` property:
![image](https://user-images.githubusercontent.com/5129564/111569742-869d5480-8760-11eb-9c06-060990432418.png)

Should be an easy fix, thanks !

**Comment by 4d61726b** [comment]
Thanks for finding this issue. I should have a fix and a new release out this weekend.

**Comment by 4d61726b** [comment]
This issue should be addressed in 2021.0.
