### ISSUE TITLE
Cannot create VirtualKD boot entry on Windows 10 x64

### ISSUE THREAD

**Issue by effolkronium** [4d61726b/VirtualKD-Redux#30]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15274763/116662273-3c81d280-a99e-11eb-9ec6-88f768fcdaf0.png)

**To Reproduce**
Run vminstall.exe and press "Install"

**Expected behavior**
It works

**Screenshots**

**Configuration (please complete the following information):**
 - VirtualKD-Redux version 2021.0
 - VMware [e.g. VMware Workstation 15.5.0 build-14665864
 - OS running on the host -- Windows 10  Pro 20H2 64-bit:
 - OS running in the guest VM -- Windows 10  Pro 2004 64-bit

**Comment by effolkronium** [comment]
I've researched the you should disable windows10 secure boot option in vmware settings (Advanced tab) in order to get it working. I'd like to see a message about this things instead of HRESULT ^^

**Comment by 4d61726b** [comment]
Thanks for reporting this issue. I went ahead and made a fix in 6a08a14d43af08fe830f8391d9e941fb38e2bbba which should detect secure boot and report back a proper error message. This will be in the next release.

**Comment by effolkronium** [comment]
Cool! Thanks
