### ISSUE TITLE
DbgBreakPoint() gets grayed on interaction

### ISSUE THREAD

**Issue by muniategui** [4d61726b/VirtualKD-Redux#31]
**Describe the bug**
DbgBreakPoint() on start appears grayed out, however after closing vmmon64.exe and reopening again it appears ungrayed. If you interact with the checkbox it gets grayed and appears unmarked however after restaring again vmmon64 it appears marked and ungrayed.

**To Reproduce**
Open vmmon64, mark 
DbgBreakPoint() on start
Check that it gets grayed (not interactuable) and not marked
Close vmmon64
Open vmmon64
Check that now its not grayed and marked

**Expected behavior**
No need to restark vmmon to mark or unmark the option

**Screenshots**
![imagen](https://user-images.githubusercontent.com/14365006/116813793-e3f53580-ab55-11eb-88bb-d6175c167146.png)
Clicked once:
![imagen](https://user-images.githubusercontent.com/14365006/116813795-e9528000-ab55-11eb-98d8-8051178c7700.png)
After closing and reopening vmmon:
![imagen](https://user-images.githubusercontent.com/14365006/116813799-f5d6d880-ab55-11eb-9fd3-74ceee7271de.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux 2021.0
 - VMWare Workstation Pro 16.1
 - Windows 10 x64 Workstation 20H2
 - Windows 10 x64 Pro 20H2

**Comment by 4d61726b** [comment]
Thanks for reporting this. The issue has been fixed in 4f0e1e89f68384ac7577f338cd5e05453a686157. The closest behavior to "-b" in Windbg Preview is "-d" and that checkbox has been aliased to that command line argument.
