### ISSUE TITLE
VirtualBoxIntegration Error

### ISSUE THREAD

**Issue by Heki6111** [4d61726b/VirtualKD-Redux#33]
When I open VirtualBoxIntegration.exe I get errors attached to txt files:
[VirtualKD-Redux-Integration-Error.txt](https://github.com/4d61726b/VirtualKD-Redux/files/7106864/VirtualKD-Redux-Integration-Error.txt)
[VirtualKD-Old-Integration-Error.txt](https://github.com/4d61726b/VirtualKD-Redux/files/7106871/VirtualKD-Old-Integration-Error.txt)
First on Redux 2021.2 and second on the legacy 3.0.
I open it in host system, VM isn't opened.
I use windows 10 19042(20H2).

**Comment by Heki6111** [comment]
It seems it was simply problem with version of vBox, I updated to 6.1.26 and it started working.
However when it is enabled windows comes to standstill even before loading animation if I launch Disable Driver Signature mode,
it work though in normal mode and works in both if I disable virtualkd integration. I use MSEdge - Win10 1809 image.
If I launch vmmon during vm boot it automatically opens windbg which prints:
[VirtualKD-Windbg-Error.txt](https://github.com/4d61726b/VirtualKD-Redux/files/7107960/VirtualKD-Windbg-Error.txt)
vmmon log window is empty.
Also restarting the host os doesn't help.

**Comment by 4d61726b** [comment]
Starting with the first issue...

Do you know what version of VirtualBox you were running before you upgraded?

**Comment by Heki6111** [comment]
I used 6.0.14-133895.
I tried installing another version of windows image of version 21H1-19043 from:
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
but it works the same way.
I also tried to install VMware Workstation Player 16.1.2-17966106.
I tried only MSEdge - Win10 1809 image on it.
It gives same result except loading comes to standstill after i open vmmon while 
it in boot manager(for previous example only Vbox integration should be enabled).
Only when I use VMware vmmon log window prints:
[Vmmon-Log-Error.txt](https://github.com/4d61726b/VirtualKD-Redux/files/7111227/Vmmon-Log-Error.txt)

**Comment by Heki6111** [comment]
I debugged it in VMware(I haven't succeed at this in Vbox).
It stays in WaitForMultipleObjectEx jumping to ZwWaitForMultipleObjects
and somehow sometimes to NtUserMsgWaitForMultipleObjectsEx.
It also goes to both RtlActivateActivationContextUnsafeFast and Deactivate version of it.
It continues in a loop.
I honestly don't know how to trace it further than that.
![WaitForMultipleObjectsEx](https://user-images.githubusercontent.com/90052271/132124515-e8cca919-c0f6-4b9f-a069-efdee6cdd313.png)
![ZwWaitForMultipleObjects](https://user-images.githubusercontent.com/90052271/132124520-70d1548e-250d-4f1a-b58e-ad75f27570f1.png)
![NtUserMsgWaitForMultipleObjectsEx](https://user-images.githubusercontent.com/90052271/132124521-463353e6-b34a-49af-beac-f0b6a9f2cab4.png)
![RtlActivateActivationContextUnsafeFast](https://user-images.githubusercontent.com/90052271/132124549-0579eecd-ef41-49ff-8bb5-529ee960e149.png)

**Comment by 4d61726b** [comment]
I resolved the first issue with commit 99b9d906fef156b3a7a87609a4360c364154908b. It seems that VirtualBox 6.1 broke backwards compatibility with 6.0 so I added a better check to ensure that users have a newer version installed.

I'm unable to reproduce your second issue. This could perhaps be something in your host environment interfering with VirtualKD-Redux. I started completely clean, with a fresh host OS (21H1). I made a small video demo of the steps I used to get it working with the same VM that you used. The only step I didn't record was adding the certificate to the host. Perhaps it's possible you missed a step or did something incorrectly when setting everything up.

Check out the video / gif here:

https://imgur.com/a/f68LW21

**Comment by Heki6111** [comment]
It was my silly mistake, I simply didn't learned how windbg works, I simply should have written g or use button go, otherwise it halts the process.
Vmware works with MSEdge Win10 and Vbox works only with WinDev2106Eval, even reinstalling MSEdge on Vbox didn't helped and it still halted, but that not a big problem.
Thank you very much.
