### ISSUE TITLE
Restore VM Snapshot error

### ISSUE THREAD

**Issue by muniategui** [4d61726b/VirtualKD-Redux#34]
**Describe the bug**
When pressing Restore VM Snapshot a message appears(photo attached)
The machine has green light, is patched and when the debuger attached it breaks perfectly.

**To Reproduce**
Launch the machine atach the debugger and so on...
Press Restore VM Snapshot

**Expected behavior**
Restore the last snapshot of the machine? I dont really know what this button should do

**Screenshots**
![imagen](https://user-images.githubusercontent.com/14365006/132760987-a9351500-c21b-4266-8882-9f2604837880.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux 2021.2
 - VMware 16.1.2
 - OS running on the host Windows 10 21H1
 - OS running in the guest Windows 10 20H2

**Comment by 4d61726b** [comment]
Thanks for reporting this issue! There was actually two bugs:

1. kdclient.dll had been renamed to kdclient32.dll a while back. There needed to be an update to the name of the DLL that gets invoked when we want to restore the last snapshot.
2. The VMware VIX COM API was deprecated many years ago. None of the COM objects VirtualKD-Redux depends on when restoring a snapshot are registered on the system. I wrote a C interface for accessing the VIX API and that is now used to restore a snapshot.

This issue has been fixed as part of 75151c2838392d25cfb16834b4677c5f74f7a296. It will be in the next release.
