### ISSUE TITLE
Vmware 15.5.1 guest VM Win7 X64 SP1 it seems didn't work

### ISSUE THREAD

**Issue by flylinfan** [4d61726b/VirtualKD-Redux#4]

**Comment by 4d61726b** [comment]
I just tried it and it worked fine. Can you be more specific about the issue that you're seeing? Have you followed the tutorial [here?](https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md)

**Comment by wumb0** [comment]
make sure to disable driver signature enforcement. if you don't it boots into windows recovery.

**Comment by 4d61726b** [comment]
I haven't been able to reproduce the problem and the lack of details or response on this ticket leads me to believe it was a user error.

If this is still an issue, please create a new ticket but ensure that you fill out the issue template.
