### ISSUE TITLE
Windbg debugging problems

### ISSUE THREAD

**Issue by chers42** [4d61726b/VirtualKD-Redux#46]
IDA and WinDBG debug my driver file together, and WinDBG only using KD dual-machine debugging, how to debug their own driver software

**Comment by 4d61726b** [comment]
I'm not sure I understand your question but take a look at:

https://hex-rays.com/blog/kernel-debugging-with-ida-pro-windbg-plugin-and-virtualkd/

This should help you get it working with IDA.
