### ISSUE TITLE
Issue with latest version of WinDBG preview

### ISSUE THREAD

**Issue by SoulXHades** [4d61726b/VirtualKD-Redux#47]
Hi! I just installed the latest version of WinDBG on my new PC. However, vmmon64.exe has WinDBG Preview radio button disabled. I tried to open the windbgx.exe via the "Sideloaded windbg preview path..." but it says system cannot open this file.
![image](https://user-images.githubusercontent.com/18703340/192925994-9c38ec86-8d17-40cd-ac82-611174b46396.png)

**Comment by 4d61726b** [comment]
I looked at the code for this and can see a potential issue that would cause the problem you are describing. Is the user that is running vmmon64.exe different than the user that installed WinDbg Preview? Are you logged in as a non-admin user?

**Comment by SoulXHades** [comment]
I am logged in as a non-admin user which WinDbg Preview is installed via the non-admin account.
![image](https://user-images.githubusercontent.com/18703340/194793374-2aca67a8-6f38-40de-bc33-e121b620b207.png)

**Comment by 4d61726b** [comment]
I believe that's the issue then. Windbg Preview is a Microsoft Store app that gets installed per user. You are running vmmon64.exe as a different user (e.g. Administrator) than the user that has Windbg Preview installed (e.g. non-admin account). You never installed it for the admin user that it's running as so vmmon64.exe will never find it and it will be grayed out.

For this case, you have two options if you want to use Windbg Preview with VirtualKD-Redux:

Option 1: Load vmmon64.exe and look at which user the application is running as. You'll need to then log in as that user to install Windbg Preview from the Microsoft Store. This is just a one-time thing you'll have to do.

OR

Option 2: Sideload Windbg Preview and use it that way.

**Comment by SoulXHades** [comment]
I decided to login as Admin to install WinDbg Preview and is now able to use WinDbg Preview with vmmon64.exe for the user account. Thank you!
