### ISSUE TITLE
Virtualbox 7 Errors

### ISSUE THREAD

**Issue by NOT-0xDECAF** [4d61726b/VirtualKD-Redux#49]
**Describe the bug**

VirtualboxIntegration throwing an error; vmmon64.exe unable to "patch VirtualBox in the fly" when launched - no VM visibility in vmmon64.exe.

**To Reproduce**
- Follow the Tutorial: https://github.com/4d61726b/VirtualKD-Redux/blob/master/VirtualKD-Redux/Docs/Tutorial.md
- As instructed, run VirtualBoxIntegration.exe, 
- Try vmmon64.exe...

**Expected behavior**
Virtualbox VM should be available/usable/visible as a VirtualKD-Redux client.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/97564918/202598294-c0a6f540-5db3-4d7f-b037-a6fba445ca38.PNG)
![Capture2](https://user-images.githubusercontent.com/97564918/202598647-a620e96c-b1ff-45dc-9980-a783ac27f55a.PNG)

**Configuration (please complete the following information):**
 - VirtualKD-Redux 2022.1
 - VirtualBox Version 7.0.2 r154219 (Qt5.15.2)
 - Host: Windows 10 21H2 19044.2251 64-bit
 - Guest: Windows 10 21H2 19044.2251 64-bit

**Additional context**
None

**Comment by 4d61726b** [comment]
I don't use VirtualBox so reports like this let me know when things are not working. I appreciate the detailed writeup.

I just released 2022.2. This should address the issue you are experiencing:

https://github.com/4d61726b/VirtualKD-Redux/releases/tag/2022.2

If that doesn't work, let me know. Thanks.

**Comment by NOT-0xDECAF** [comment]
Confirmed, all working now, thank you <3
