### ISSUE TITLE
Debugger can't start normally

### ISSUE THREAD

**Issue by xia0ji233** [4d61726b/VirtualKD-Redux#51]
**Describe the bug**
I did operations according to README file,but get unexpected result.

**To Reproduce**
1. Create Virtual Machine in Vmware Workstation 16.2.4 build-20089737 pro.
2. ISO file was downloaded from https://www.microsoft.com/zh-cn/software-download/windows10ISO,the version is Windows10 22H2
3. Running the file in target64 on this Virtual Machine,and an entry was created normally.
4. Then I start vmmon64.exe on my physical machine, successfully patched but can't connenct to windbg.

**Expected behavior**
windbg will auto start and connect the virtual machine normally

**Screenshots**
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/73569212/1741a786-278b-48c8-93f9-8444d5013bc3)

I have searched in google and issue in this project but get no result for me.I would appreciate it very much if someone could give me some helpful advice

**Comment by 4d61726b** [comment]
From your screenshot, it seems like `kdclient.dll` was successfully loaded on your host.

Can you:

1. Start `vmmon64.exe` before powering on any VMs.
2. Power on the VM, make sure `vmmon64.exe` reports success for your VM before moving on to the next step. Just look for the green circle in the PID column.
3. In the VM at the "Windows Boot Manager" screen, ensure the `[VKD-Redux]` entry is highlighted **then** press F8 and select "Disable Driver Signature Enforcement".

**Comment by xia0ji233** [comment]
Following your steps,I see the problem.I didn't press F8 and select "Disable Driver Signature Enforcement" option when it start.So I can connect to windbg when I follow your steps.Mabey most tutorials online don't metion this detail,so I only choose the   new entry when the virtual machine booting.
Thank you very much for your help.Best wishes.
