### ISSUE TITLE
It is getting stuck every now and then

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#54]
Every now and then (more now than then), when I shut down a VM, the status of the VM in VirtualKD is showing as green and the WinDbg window isn't closing even though I have it set to do so when the VM is shut down.

**Comment by 4d61726b** [comment]
Can you post a screenshot of the WinDbg window when this happens?

**Comment by Zero3K** [comment]
It just says Waiting to reconnect when I shut the VM down via the OS or the last debug output if I close it.

**Comment by 4d61726b** [comment]
- Which hypervisor are you using and what is the version?
- Which version of WinDbg are you using?

**Comment by Zero3K** [comment]
1. VirtualBox 6.1.45.
2. 6.12.0002.633
3. By the way, the OS column of the VM in VirtualKD's window is stuck as yes.

**Comment by Zero3K** [comment]
Any news?

**Comment by 4d61726b** [comment]
I am planning to look at this in the next few weeks. I have a couple things specifically for VirtualBox that I'd like to address for the next release.

**Comment by Zero3K** [comment]
It's really bad at the moment.

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by 4d61726b** [comment]
I have free time today to triage this so I will see if I can figure it out and produce a fix

**Comment by 4d61726b** [comment]
This has been fixed in 2024.0
