### ISSUE TITLE
Ability to set the symbol and source paths per VM

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#55]
It would be nice if a user could set the symbol and source paths for a VM so that way WinDbg will always be looking for the proper PDBs and showing the correct source code.

**Comment by 4d61726b** [comment]
Seems possible to do via the command line options available to WinDbg and WinDbg Preview:

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-command-line-options
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-command-line-preview

In the meantime, you can already do this with WinDbg Workspaces. Configure the symbol and source paths for a particular VM and then save that configuration to a workspace for that VM. When you attach to that VM again in the future, load the workspace associated with it.
