### ISSUE TITLE
Here are a bunch of crash dumps

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#58]
*subject*

[CrashDumps.zip](https://github.com/4d61726b/VirtualKD-Redux/files/13759768/CrashDumps.zip)

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by Zero3K** [comment]
Well?

**Comment by 4d61726b** [comment]
I triaged and figured out this issue, I will address it soon as it's related to #54

**Comment by 4d61726b** [comment]
This has been fixed in 2024.0
