### ISSUE TITLE
Red light on Windows 10 x64 guest running in Vmware workstation 15.5.2

### ISSUE THREAD

**Issue by cythrauL** [4d61726b/VirtualKD-Redux#6]
Hi,

I've followed your tutorial, booted the guest using the correct boot option, disabled driver signing, and am running vmmonitor.

Unfortunately, the light under PID is red, and there are no messages at all in the debug message window.

Hitting run debugger does nothing.

Has vmware workstation 15.5.2 broken this app?

**Comment by 4d61726b** [comment]
I just tried it on 15.5.2 and had no issues.

There should always be some kind of message output **but** if vmmon64 has ran already (either successfully or unsuccessfully) and is terminated and ran again, then there may not be output until the VM is shutdown. That behavior is expected.

For the purpose of troubleshooting this issue:

1. Shut down the guest.
2. Reboot your host.
3. Start only one instance of vmmon64.exe (Confirm that there are no PIDs).
4. Open VMware Workstation and start the guest. At this point there should be debug output from vmmon64 that you can post here if there is an error.

If you can't get debug output from that then I will have a few more questions.

**Comment by cythrauL** [comment]
For reasons I don't understand, restarting the host has fixed the issue, thanks.

**Comment by 4d61726b** [comment]
Good to hear that it works now.

You can reopen this issue if it happens again and we can troubleshoot it from there, as there were a few more things we could have tried without rebooting the host in an attempt to expose the problem.
