### ISSUE TITLE
Fixing ReactOS' support of it

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#61]
It complains that ReactOS is using an older version of its driver when I try to use the proper boot menu entry. Please either make a ticket on its JIRA and/or fix it.

**Comment by 4d61726b** [comment]
Can I see a screenshot of the error?

**Comment by Zero3K** [comment]
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/6194332/d5ac4fcf-122e-445f-ab23-afe1c2eb7f62)

**Comment by 4d61726b** [comment]
Can you pull `kdcom.dll` and `kdbazis.dll` from the VM and attach them here?

**Comment by Zero3K** [comment]
There's no kdbazis.dll but there is a kdvbox.dll. I am attaching an archive containing kdcom.dll and kdvbox.dll.

[kdcom.zip](https://github.com/4d61726b/VirtualKD-Redux/files/14474608/kdcom.zip)

**Comment by 4d61726b** [comment]
What happens when you replace `kdcom.dll` on the guest with `kdbazis.dll` from the `target32` folder in the VKD release and do a debug boot? Does it work?

**Comment by Zero3K** [comment]
1. It still gives the same error.
2. Replacing kdvbox.dll with it results in this:
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/6194332/2f47021f-b6ed-4b47-aee2-2451a1f28668)

**Comment by Zero3K** [comment]
Can this be fixed or not?

**Comment by 4d61726b** [comment]
I have not triaged this, so I can't say whether or not it can be addressed. I don't use ReactOS at all so it's not on my list of priorities at the moment.

**Comment by Zero3K** [comment]
Okay.

**Comment by 4d61726b** [comment]
Support for ReactOS has been added in [2024.2](https://github.com/4d61726b/VirtualKD-Redux/releases/tag/2024.2)
