### ISSUE TITLE
Does not recognize virtual machines 

### ISSUE THREAD

**Issue by UIWP0** [4d61726b/VirtualKD-Redux#64]
**Describe the bug**
Local OS machine is Windows 10, using VirtualKD-Redux-2024.0 + Vmware16 Pro -16.2.4 build-20089737 to debug Windows 10 VMs, but VirtualKD-Redux doesn't recognize any of the VMs opened

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/32759429/a6e6ae36-cfe9-4bf6-b7fe-b216cf735e04)

**Configuration (please complete the following information):**
 - VirtualKD-Redux-2024.0:
 - VMware Workstation Pro 16.2.4 build-20089737:
 - Windows 10  22H2 64-bit
 - Windows 10  21H2 64-bit and Windows xp 32-bit:

**Additional context**
:=(

**Comment by 4d61726b** [comment]
When this happens, can you run the following Powershell as Administrator and then attach the `processes.log` that it generates to this issue ticket?

```powershell
Get-Process | ForEach-Object {
    $wmiProcess = Get-WmiObject Win32_Process -Filter "ProcessId = $($_.Id)"
    $user = $wmiProcess.GetOwner().User
    $commandLine = $wmiProcess.CommandLine
    Write-Output "$user`t`t:`t$commandLine"
} | Out-File -FilePath "processes.log"
```

**Comment by 4d61726b** [comment]
Closing due to no response to the request. I'm going to assume it was something on your host that was blocking `vmmon` from enumerating processes.
