### ISSUE TITLE
[REGRESSION] VMs aren't being properly hooked into under VirtualBox 7.0.15

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#66]
**Describe the bug**
The hooking DLL assigned to the VM is not working properly. It is either not being loaded by VirtualBox or has a new/regressed bug in it.
 
**To Reproduce**
Follow the steps in the documentation.

**Expected behavior**
WinDBG should be ran and showing the debug output of the OS.

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2019.4]: 2024.2
 - VMware or VirtualBox version [e.g. VMware Workstation 15.5.0 build-14665864]: VirtualBox 7.0.15
 - OS running on the host [e.g. Windows 10 1903 64-bit]: Windows 7 SP1 64-bit
 - OS running in the guest VM [e.g. Windows 7 SP1 32-bit]: Windows 7 SP1 32-bit/ReactOS

**Additional context**

**Comment by 4d61726b** [comment]
> The hooking DLL assigned to the VM is not working properly.

Works fine for me. Going to need you to be more specific here.

**Comment by Zero3K** [comment]
I mean, it shows up as Red in the VMMon program.

**Comment by 4d61726b** [comment]
Make sure you are using the new one. Toggle it to Disable and then back to Enable.

**Comment by Zero3K** [comment]
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/6194332/f0c371a6-3a77-4210-91d9-286063e2954b)

**Comment by Zero3K** [comment]
> Make sure you are using the new one. Toggle it to Disable and then back to Enable.

I did do that.

**Comment by 4d61726b** [comment]
I think I see the issue, I'll post an update shortly.

**Comment by 4d61726b** [comment]
Try it now with the latest release binaries that were just published.

VirtualBox requires the binaries to be signed. The issue was that the binaries pushed to Github did not get signed (but the ones I used for testing were).

**Comment by Zero3K** [comment]
The latest release binaries work as expected. Thanks for fixing it.
