### ISSUE TITLE
Is it possible for it to support VirtualBox 6.0.24?

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#67]
*subject*

**Comment by 4d61726b** [comment]
That version is EoL correct? [This has been the official project policy on version support](https://github.com/4d61726b/VirtualKD-Redux/issues/44#issuecomment-1126714272).

That being said, what kind of error do you get on that older version? Is it an error when you try to start `VirtualBoxIntegration`?

**Comment by Zero3K** [comment]
It tells me to use v 6.1.x or above. I wonder how far back you can support.

**Comment by 4d61726b** [comment]
You can try this:
[VirtualBox6_Integration.zip](https://github.com/user-attachments/files/16046636/VirtualBox6_Integration.zip)

You would have to ensure you copy and overwrite the latest one you have now. It has to execute in the same directory.

**Comment by 4d61726b** [comment]
I forgot to mention:

You may have to also rename `kdclient32.dll` to `kdclient.dll`.

**Comment by Zero3K** [comment]
I renamed kdclient64.dll to kdclient.dll and am getting a bunch of error sounds but no dialog box(es). Also, I tried downgrading to 6.0.22 because of a memory error that happens when I enable 3D Acceleration and use the VGA Driver in the Display section. The error still happens though.

**Comment by 4d61726b** [comment]
No, `kdclient64.dll` does not change and stays the same. Instead, you must rename `kdclient32.dll` to `kdclient.dll`.

I would try again:

1. Download a new copy of 2024.3 and unzip it to a new directory.
3. Rename `kdclient32.dll` to `kdclient.dll`.
4. Download `VirtualBox6_Integration.zip` that is attached to this issue ticket and unzip it to the directory, overwriting the one shipped with 2024.3.

Make sure you are operating out of this directory for running `VirtualBox6_Integration.exe` and `vmmon64.exe`.

Toggle Enable -> Disable -> Enable on the VM in `VirtualBox6_Integration` just in case something is stuck (The binary was rebuilt off a much older tag so I don't recall what bugs it had back then).

**Comment by Zero3K** [comment]
I also renamed kdclient32.dll to kdclient.dll. The same error sounds were heard.

**Comment by 4d61726b** [comment]
Closing as this version of VirtualBox is EoL and no longer supported
