### ISSUE TITLE
24H2 desktop cannot be displayed

### ISSUE THREAD

**Issue by StyGame** [4d61726b/VirtualKD-Redux#68]
**Describe the bug**
24H2 can be started, windbg has output, and the desktop cannot be displayed for a long time after entering the system. However, the COM port debugging can be entered into the system to display the desktop after normal configuration.

**Expected behavior**
Enter system debugging mode normally

**Screenshots**
![image](https://github.com/user-attachments/assets/3635810c-d2a9-41a8-9fe1-d54e4f62f2a9)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2024.3]:
 - VMware or VirtualBox version [e.g. VMware Workstation 16 Pro 16.2.3 build-19376536]:
 - OS running on the host [e.g. Windows 11 24H2 26100.1742 64-bit]:
 - OS running in the guest VM [e.g.Windows 11 24H2 26100.1742 64-bit]:

**Comment by 4d61726b** [comment]
I'm not able to reproduce this.

Did you upgrade from a previous version of Windows? What's the size (in bytes) of `C:\Windows\System32\kdcom.dll`?

**Comment by StyGame** [comment]
Yes, the system was upgraded from 15063 to 26100, the size of kdcom.dll is
![image](https://github.com/user-attachments/assets/9c803b77-58fb-42d2-8ceb-9812c9ee94e8)
digital signature
![image](https://github.com/user-attachments/assets/b1917dad-d7fb-4fe9-a04c-49917b86f2a4)
file
[kdcom.zip](https://github.com/user-attachments/files/17352636/kdcom.zip)
reappear video
https://youtu.be/m4OSeW5wQRw

**Comment by 4d61726b** [comment]
`kdcom.dll` was replaced on upgrade and you will need to re-run `vminstall.exe`.

**Comment by StyGame** [comment]
Let me correct my previous misunderstanding. In the virtual machine, the kdcom.dll file size is the correct replacement size. My previous screenshot is the kdcom.dll size in the host machine.
![image](https://github.com/user-attachments/assets/ba71366d-32b8-4224-b0ff-019c625b9e34)
The reproduction video shows the steps from running vminstall.exe to restart failure.
