### ISSUE TITLE
High CPU while debugging a VM with 2 cores per processor

### ISSUE THREAD

**Issue by repnz** [4d61726b/VirtualKD-Redux#8]
**Describe the bug**

After I run vminstall.exe and reboot for debugging, the vmware-vmx.exe process constantly takes ~12% cpu when I stop on a breakpoint. When I resume execution, the CPU usage is not high. Also, when I resume execution the Poll Rate is around 63 - is it normal? Can you explain a bit about the Poll Rate? 

I tried to to analyze the problem and then I figured out that the problem only happens when "Number Of Cores Per Processor" is not 1. 

**To Reproduce**
1. Install a vm and configure "Number Of Cores Per Processor" to 2
2. Run vminstall.exe
3. Run bcdedit /debug on
4. bcdedit /dbgsettings serial debugport:1 baudrate:115200
5. Restart VM and hit ALT-DELETE (Windbg Preview) 
6. The cpu goes high.

**Expected behavior**
I expect that CPU will be 0..

**Screenshots**

Not in break:
![image](https://user-images.githubusercontent.com/35385002/79351577-82a9f680-7f41-11ea-8948-9bd865374cc6.png)

During break:

![image](https://user-images.githubusercontent.com/35385002/79351662-9ead9800-7f41-11ea-9202-c7175b5aec34.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version: 2019.6
 - Vmware Workstation 15.5.2 build-15785246
- Debugger: Windbg Preview / kd.exe
 - OS running on the host: Windows 10.0.18363.657
 - OS running in the guest VM: Windows 10 - it happened in different versions of windows 10 build 19603 and RS5.

*Context*

```
*************************************************************************************
*VirtualKD-Redux patcher DLL successfully loaded. Patching the GuestRPC mechanism...*
*************************************************************************************
Searching patch database for information about current executable...
No information found.
Waiting for VMWare to initialize (5900 ms more to wait)
Analyzing VMWARE-VMX executable...
Building list of EXE sections... 21051K of data found.
Scanning for RPC command name strings...
Finished scanning. Found 56 strings.
Searching for string references...
Found 31 string references.
Found 3 structures resemblant to RPC dispatcher table.
(address 00007FF61EFF4C38, matched pointers: 1)
(address 00007FF61EFF4C48, matched pointers: 1)
(address 00007FF61F445410, matched pointers: 29)
Analyzing potential RPC dispatcher tables...
Potential RPC table analysis complete. Found 1 candidates.
(address 00007FF61F4447E0, entries: 110, free entries: 36)
Using RPC dispatcher table at 0x7FF61F4447E0 (110 entries)
Waiting for RPC table to be initialized by VMWare...
RPC table initialized. Patching it...
Successfully patched entry #1
VMWare reset monitor activated...
```

I tried to understand which thread in vmware-vmx is the high CPU thread and it looks like it's some code inside vmware-vmx.exe that runs in a loop calling DeviceIoCtl to vmx86.sys (looks like a function called RunVM of VCPU) - If I suspend this thread, the VM won't have high CPU (obviously) but when I try to resume the debugger the VM gets stuck, looks like it's the thread that's responsible for virtualizing one of the virtual CPUs. I then noticed that the VM was configured for 2 cores per processor. When I changed it to 1, the problem was solved.

**Comment by 4d61726b** [comment]
1. I'm able to reproduce this issue without VirtualKD-Redux installed in the VM and even without vmmon running. If you enable KDNET on the guest VM the vmx process will stay at a steady 12% when the debugger is broken in. Additionally, I'm able to reproduce this issue at the Windows 10 Boot Menu, without any debugging enabled. You're correct, the thread belongs to VMware Workstation spinning on DeviceIoControl calls to the virtualization driver (vmx86.sys). This is a VMware Workstation issue and not a VirtualKD-Redux issue. If you are able to suspend that thread with no repercussions, a potential solution could be to have either kdclient or vmmon find and suspend that thread when the debugger is broken into the guest machine and unsuspend when execution is to resume. I'd want to know more information about the call that the vmx thread is spinning on before making that kind of decision.

2. The bcdedit steps you're performing are no longer necessary. VirtualKD-Redux automatically fixes up the BCD (something that VirtualKD did not do properly on newer versions of Windows 10).

3. The behavior you are seeing with the poll rate is normal. The poll rate just has to do with gathering statistics in a debugging session. When KdReceivePacket() is called with KdCheckForAnyPacket, it checks whether any data can be received from WinDbg and returns immediately. The poll rate represents how many times this event occurs. You can read more about this here: http://sysprogs.com/legacy/articles/kdvmware/kdcom.shtml

**Comment by repnz** [comment]
Thank you for your answer 👍
